### ISSUE TITLE
Identity and Access - Collection of drivers/tools

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/motorcyclejs#23]
Identity and Access is central to applications and can be abstracted to facilitate common functionality.

Given the new `run()` type signature, we are now able to define Components, in the same fashion as we do for our `main` function, for our `effects` function with the type signature `Sinks -> Sources`.  

## Identity and Access Components to implement

- [x] Register a user --- Username / Password
- [x] Deregister a user
- [x] Sign In
- [x] Sign Out
- [ ] Change password
- [ ] Get current user

Progress can be tracked on #24

**Comment by TylorS** [comment]
@Frikki Do we want to abandon this issue? Since we both know there are issues with trying to accomplish such a broad abstraction outside of a given domain.

**Comment by Frikki** [comment]
@TylorS I think so. Abstractions can be OK, but in this case, I think it isn’t. Feel free to close the issue as well as the PR #24 . However, I’d like to keep the branch alive for a little longer.

**Comment by TylorS** [comment]
Okay, closing without deleting the branch.
