### ISSUE TITLE
Text nodes under isolated tree cause crash during vdom update

### ISSUE THREAD

**Issue by milankinen** [motorcyclejs/motorcyclejs#27]
**Code to reproduce the issue:**

See #26 

**Expected behavior:**

UI updates correctly after slider has been moved

**Actual behavior:**

Crash. Probably caused because the slider's vtree is isolated, thus its root node has `scope` which is inherited to the children in [hyperscript helper](https://github.com/TylorS/mostly-dom/blob/2dcca4d97289415ce5f7664e0db15221b475287f/src/hyperscript/h.ts#L69-L70). Howerever vnode's update function blindly [tries to set scope](https://github.com/TylorS/mostly-dom/blob/2dcca4d97289415ce5f7664e0db15221b475287f/src/patchVNode/updateElement.ts#L12-L13) by using `Element.setAttribute` although text nodes (children that inherit the scope attribute in hyperscript helper) don't have one.

**Versions of packages used:**

    "@culli/store": "latest",
    "@cycle/isolate": "^1.4.0",
    "@motorcycle/dom": "^7.0.6",
    "@motorcycle/run": "^1.2.5",

**Comment by TylorS** [comment]
This particular issue should be solved with mostly-dom v1.3.1

**Comment by milankinen** [comment]
Working now 👍
