### ISSUE TITLE
Add I/O / Gateway / Effectful Component Sink Types

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcyclejs#30]
When defining types, such as `MainSinks`, we now have to explicitly tell that at sink is a `Stream` of something that an I/O / gateway / effectful component (a.k.a. _driver_) requires; for example:

```
interface MainSinks {
  view$: Stream<VNode>;
  localStorage$: Stream<LocalStorageCommand>;
}
```

It also, in turn, requires us to `import { Stream } from 'most'`. This seems like unnecessary boilerplate. Instead, we could let the I/O / gateway / effectful component export the sink type, which it requires, e.g., `LocalStorageSink` or `DomSink`.

**Comment by TylorS** [comment]
I think we could do this even better if we start to move all of the driver towards being component functions.

```typescript
import { DomSinks } from '@motorcycle/dom';
import { LocalStorageSinks } from '@motorcycle/local-storage';

export type MainSinks = 
  DomSinks & LocalStorageSinks;
```

What do you think?

**Comment by Frikki** [comment]
Yes. I think: yes!

**Comment by kaosat-dev** [comment]
Sorry if I am very daft, but what are component functions ?

**Comment by TylorS** [comment]
In Cycle, components a really just functions of `Sources -> Sinks`, but in Motorcycle we've introduced "effectful" components, the second argument to run(), that are `Sinks -> Sources`

**Comment by Frikki** [comment]
This implementation gives us a lot of freedom on how drivers / "effectful" components / I/O gateways (whatever we’ll call them) are made. A key aspect is that we don’t interlock ourselves with the drivers’ object.

At the moment, we are making the TodoMVC following this concept, while at the same time illustrating how larger application may be architected (even though the TodoMVC doesn’t qualify for such an architecture).

**Comment by kaosat-dev** [comment]
ok thanks for the infos @TylorS
