### ISSUE TITLE
`useCapture` not behaving as intended, maybe?

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcyclejs#33]
I wonder if motorcyclejs suffers the same as reported in this issue https://github.com/cyclejs/cyclejs/issues/522, and as seen in the demonstration below.

https://esnextb.in/?gist=d6e1d3ae7c686cc51e294f9247910548

We should create a similar gist to check.

**Comment by TylorS** [comment]
Nope. https://esnextb.in/?gist=3b64c64a95090381e6aa41ef92ea5fbc
