### ISSUE TITLE
Update external package READMEs 

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/motorcyclejs#36]
Other repositories, such as https://github.com/motorcyclejs/dom, need their READMEs to be updated to mark them as deprecated with links pointing here to the monorepo.

- [x] [dom](https://github.com/motorcyclejs/dom)
- [x] [run](https://github.com/motorcyclejs/run)
- [x] [router](https://github.com/motorcyclejs/router)
- [x] [history](https://github.com/motorcyclejs/history)
- [x] [http](https://github.com/motorcyclejs/http)
- [x] [core](https://github.com/motorcyclejs/core)

**Comment by TylorS** [comment]
Should we also mark [core](https://github.com/motorcyclejs/core) as deprecated? It doesn't have any bugs, but maybe should be left simply because it still works.

**Comment by Frikki** [comment]
Perhaps mark it "Will be deprecated when bla bla reaches vX.Y or milestone Z".

**Comment by Frikki** [comment]
What do we do about core then?

**Comment by Frikki** [comment]
Deprecated core and closing
