### ISSUE TITLE
Remove user exercises across Basic Usage examples

### ISSUE THREAD

**Issue by mjleitch** [motorcyclejs/motorcyclejs#59]
I just wanted to suggest replacing all instances of '// left as an user exercise' with the actual working solution in the 'Basic Usage' examples across all motorcyclejs packages.

Basic examples should act as a sanity check for beginners by providing simple but complete samples they can import and run without having to ask themselves "Am I doing it wrong? Or is there something wrong with the example?"

I do think encouraging this type of self exploration can only make for stronger developers with deeper knowledge of the framework ...but this is the wrong place, IMO.

**Comment by TylorS** [comment]
Hello @mjleitch thanks for the feedback. I totally agree with you. We're actually hard at work on revamping all of our documentation (among other things) as we speak.

**Comment by mjleitch** [comment]
Great! Really glad to see motocycle moving forward... 

I'd love to help if you ever need it. I haven't done much contribution to date, but I'm looking to get my feet wet... Please let me know if you've got anything stupid simple I could take a stab at.

**Comment by TylorS** [comment]
Hey @mjleitch, if you're interested in helping out, reach out to us on gitter 😄 
https://gitter.im/motorcyclejs/motorcyclejs
